redis: &redis
  adapter: redis
  url: redis://localhost:6379/1

development: *redis
test: *redis

production:
  adapter: redis
  url: <%= ENV["REDIS_URL"] %>
  channel_prefix: action_cable_demo_production
